### ISSUE TITLE
WOW Stats don't calculate if you didn't do a workout last week

### ISSUE THREAD

**Issue by drewbennison** [drewbennison/pelotonR#1]
If you work out on Monday of Week 2, but didn't work out on Monday of Week 1, it won't display data. This might be the behavior we want, but just wanted to talk about it.

**Comment by kylebennison** [comment]
i believe you added NA handling, so we can probably close @drewbennison.

However, i've found random times where I believe it should be showing me WOW stats and instead is saying not enough data. Unsure of cause right now - thought it had something to do with whether you had a live ride or not but that doesn't seem to be the case.

**Comment by drewbennison** [comment]
Moved to the new issue you started,
